// ACTIONS - actionTypes.js

export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_CURRENT_GAME_SUCCESS = "FETCH_CURRENT_GAME_SUCCESS";
export const START_NEW_GAME = "START_NEW_GAME";
export const REGISTER_MOVE = "REGISTER_MOVE";
